- name: Include vars
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - include_vars: vars.production.yaml
  tags:
  - pageserver
  - safekeeper

- name: Discover storage nodes
  import_playbook: common/discover.storage.yaml

- name: Deploy
  import_playbook: common/deploy.storage.yaml
