[package]
name = "zenith_utils"
version = "0.1.0"
authors = ["Eric Seppanen <eric@zenith.tech>"]
edition = "2018"

[dependencies]
tokio = { version = "1.5", features = ["sync", "time" ] }
thiserror = "1"

[dev-dependencies]
tokio = { version = "1.5", features = ["macros", "rt"] }
