[workspace]
members = [
    "compute_tools",
    "control_plane",
    "pageserver",
    "proxy",
    "safekeeper",
    "storage_broker",
    "workspace_hack",
    "libs/*",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_with = "2.0"
humantime-serde = "1.1.1"
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
once_cell = "1.13"
nix = "0.25"
bytes = "1.0"
byteorder = "1.4"
rand = "0.8"
futures = "0.3"
async-stream = "0.3"
async-trait = "0.1"
routerify = "3"
signal-hook = "0.3"
rustls = "0.20"
pin-project-lite = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1.4"
clap = "4.0"
git-version = "0.3"
tar = "0.4"
url = "2.2"
const_format = "0.2"
parking_lot = "0.12"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
humantime = "2.1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
hyper = "0.14"
hyper-tungstenite = "0.8.1"
toml_edit = { version = "0.14", features = ["easy"] }
postgres = { git = "https://github.com/neondatabase/rust-postgres.git", rev="43e6db254a97fdecbce33d8bc0890accfd74495e" }
tokio-postgres = { git = "https://github.com/neondatabase/rust-postgres.git", rev="43e6db254a97fdecbce33d8bc0890accfd74495e" }
postgres-protocol = { git = "https://github.com/neondatabase/rust-postgres.git", rev="43e6db254a97fdecbce33d8bc0890accfd74495e" }
postgres-types = { git = "https://github.com/neondatabase/rust-postgres.git", rev="43e6db254a97fdecbce33d8bc0890accfd74495e" }
tokio-util = { version = "0.7", features = ["io"] }
tokio-stream = "0.1"
tokio-rustls = "0.23"
tokio-tar = { git = "https://github.com/neondatabase/tokio-tar.git", rev="404df61437de0feef49ba2ccdbdd94eb8ad6e142" }
hex = "0.4"
hex-literal = "0.3"
rustls-split = "0.3"
crc32c = "0.6"
itertools = "0.10"
rustls-pemfile = "1"
###
log = "0.4"
env_logger = "0.9"
###
sentry = { version = "0.29", default-features = false, features = ["backtrace", "contexts", "panic", "rustls", "reqwest" ] }
prometheus = {version = "0.13", default_features=false, features = ["process"]} # removes protobuf dependency
bincode = "1.3"
jsonwebtoken = "8"
strum = "0.24"
strum_macros = "0.24"
libc = "0.2"
memoffset = "0.7"
notify = "5.0.0"
tokio = { version = "1.17", features = ["macros"] }
tokio-postgres-rustls = "0.9.0"
futures-core = "0.3"
futures-util = "0.3"
tonic = {version = "0.8", features = ["tls", "tls-roots"]}
prost = "0.11"
fs2 = "0.4.3"
bindgen = "0.61"
toml = "0.5"
comfy-table = "6.1"
md5 = "0.7.0"
hmac = "0.12.1"
hashbrown = "0.12"
bstr = "1.0"
atty = "0.2.14"
base64 = "0.13.0"
close_fds = "0.3.2"
fail = "0.5.0"
crossbeam-utils = "0.8.5"
num-traits = "0.2.15"
rstar = "0.9.3"
scopeguard = "1.1.0"
sha2 = "0.10.2"
socket2 = "0.4.4"
uuid = { version = "1.2", features = ["v4", "serde"] }
webpki-roots = "0.22.5"
x509-parser = "0.14"
tls-listener = { version = "0.5.1", features = ["rustls", "hyper-h1"] }
walkdir = "2.3.2"
aws-smithy-http = "0.51.0"
aws-types = "0.51.0"
aws-config = { version = "0.51.0", default-features = false, features=["rustls"] }
aws-sdk-s3 = "0.21.0"
svg_fmt = "0.4.1"

metrics = { version = "0.1", path = "./libs/metrics/" }
pageserver_api = { version = "0.1", path = "./libs/pageserver_api/" }
safekeeper_api = { version = "0.1", path = "./libs/safekeeper_api" }
postgres_connection = { version = "0.1", path = "./libs/postgres_connection/" }
postgres_ffi = { version = "0.1", path = "./libs/postgres_ffi/" }
pq_proto = { version = "0.1", path = "./libs/pq_proto/" }
remote_storage = { version = "0.1", path = "./libs/remote_storage/" }
# Note: main broker code is inside the binary crate, so linking with the library shouldn't be heavy.
storage_broker = { version = "0.1", path = "./storage_broker/" }
tenant_size_model = { version = "0.1", path = "./libs/tenant_size_model/" }
utils = { version = "0.1", path = "./libs/utils/" }

workspace_hack = { version = "0.1", path = "./workspace_hack/" }

tempfile = "3.2"
tonic-build = "0.8"
criterion = "0.4"
rcgen = "0.10"
rstest = "0.15"

[profile.release]
# This is useful for profiling and, to some extent, debug.
# Besides, debug info should not affect the performance.
debug = true

# disable debug symbols for all packages except this one to decrease binaries size
[profile.release.package."*"]
debug = false

[profile.release-line-debug]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
[profile.release-line-debug-lto]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
lto = true

[profile.release-line-debug-size]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
opt-level = "s"
[profile.release-line-debug-zize]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
opt-level = "z"
[profile.release-line-debug-size-lto]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
opt-level = "s"
lto = true
[profile.release-line-debug-zize-lto]
inherits = "release"
debug = 1 # true = 2 = all symbols, 1 = line only
opt-level = "z"
lto = true

[profile.release-no-debug]
inherits = "release"
debug = false # true = 2 = all symbols, 1 = line only

[profile.release-no-debug-size]
inherits = "release"
debug = false # true = 2 = all symbols, 1 = line only
opt-level = "s"
[profile.release-no-debug-zize]
inherits = "release"
debug = false # true = 2 = all symbols, 1 = line only
opt-level = "z"

[profile.release-no-debug-size-lto]
inherits = "release"
debug = false # true = 2 = all symbols, 1 = line only
opt-level = "s"
lto = true

[profile.release-no-debug-zize-lto]
inherits = "release"
debug = false # true = 2 = all symbols, 1 = line only
opt-level = "z"
lto = true


# This is only needed for proxy's tests.
# TODO: we should probably fork `tokio-postgres-rustls` instead.
[patch.crates-io]
tokio-postgres = { git = "https://github.com/neondatabase/rust-postgres.git", rev="43e6db254a97fdecbce33d8bc0890accfd74495e" }
