[workspace]
members = [
    "compute_tools",
    "control_plane",
    "pageserver",
    "postgres_ffi",
    "proxy",
    "walkeeper",
    "workspace_hack",
    "zenith",
    "zenith_metrics",
    "zenith_utils",
]

[profile.release]
# This is useful for profiling and, to some extent, debug.
# Besides, debug info should not affect the performance.
debug = true
