[package]
name = "zenith_metrics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = "0.12"

[dev-dependencies]
lazy_static = "1.4.0"
