name: 'Get Endpoint'
description: 'Get Endpoint ID from project using API'

inputs:
  api_key:
    description: 'Neon API key'
    required: true
  project_id:
    description: 'ID of the Project to create Branch in'
    required: true
  api_host:
    description: 'Neon API host'
    default: console-stage.neon.build
outputs:
  id:
    description: 'Endpoint ID'
    value: ${{ steps.get-endpoint.outputs.id }}
  branch_id:
    description: 'Branch ID'
    value: ${{ steps.get-endpoint.outputs.branch_id }}

runs:
  using: "composite"
  steps:
    - name: Get Endpoint ID
      id: get-endpoint
      shell: bash -euxo pipefail {0}
      run: |
        for i in {1..10}; do
         res=$(curl \
            "https://${API_HOST}/api/v2/projects/${PROJECT_ID}/endpoints" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${API_KEY}")
        
         endpoint_id=$(echo $res | jq '.endpoints[0].id')
         branch_id=$(echo $res | jq '.endpoints[0].branch_id')
          

         if [ -z "${endpoint_id}" ] || [ "${endpoint_id}" == "null" ]; then
           sleep 1
           continue
         fi

          break
        done

        if [ -z "${endpoint_id}" ] || [ "${endpoint_id}" == "null" ]; then
          echo >&2 "Failed to get endpoint id after 10 attempts"
          exit 1
        fi

        echo "id=${endpoint_id}" >> ${GITHUB_OUTPUT}
        echo "branch_id=${branch_id}" >> ${GITHUB_OUTPUT}

      env:
        API_HOST: ${{ inputs.api_host }}
        API_KEY: ${{ inputs.api_key }}
        PROJECT_ID: ${{ inputs.project_id }}
