# Helm chart values for neon-proxy-scram.
# This is a YAML-formatted file.

image:
  repository: neondatabase/neon

settings:
  authBackend: "console"
  authEndpoint: "http://console-staging.local/management/api/v2"
  domain: "*.cloud.stage.neon.tech"

# -- Additional labels for neon-proxy pods
podLabels:
  zenith_service: proxy-scram-legacy
  zenith_env: dev
  zenith_region: us-east-2
  zenith_region_slug: us-east-2

exposedService:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: neon-proxy-scram-legacy.beta.us-east-2.aws.neon.build

#metrics:
#  enabled: true
#  serviceMonitor:
#    enabled: true
#    selector:
#      release: kube-prometheus-stack
