useCertManager: true

replicaCount: 3

exposedService:
  # exposedService.port -- Exposed Service proxy port
  port: 4432
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
    external-dns.alpha.kubernetes.io/hostname: "*.snirouter.alpha.eu-central-1.internal.aws.neon.build"

settings:
  domain: "*.snirouter.alpha.eu-central-1.internal.aws.neon.build"
  sentryEnvironment: "staging"

imagePullSecrets:
  - name: docker-hub-neon

metrics:
  enabled: false
