version: "3"
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    # ports:
    #   - "9090:9090"
    # TODO: find a proper portable solution
    network_mode: "host"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    # ports:
    #   - "3000:3000"
    # TODO: find a proper portable solution
    network_mode: "host"
