
blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://console.neon.tech/app/projects?modal=feedback
    about: For feature requests in the Neon product, please submit via the feedback form on `https://console.neon.tech`
