name: "Check submodule reference"
description: "Check that submodule references a commit in a submodule repository's branch"

inputs:
  submodule_path:
    description: "directory with the submodule"
    required: true
  branch:
    description: "branch in the submodule repository"
    required: true

runs:
  using: "composite"

  steps:
    - name: Check ${{ inputs.submodule_path }} submodule reference
      shell: bash -euxo pipefail {0}
      run: |
        cd ${{ inputs.submodule_path }}
        git fetch origin "refs/heads/${{ inputs.branch }}:refs/heads/origin/${{ inputs.branch }}"
        RC=$(git merge-base --is-ancestor origin/${{ inputs.branch }} HEAD; echo $?)
        if [ "$RC" != "0" ]; then
          echo "${{ inputs.submodule_path }} submodule is not an ancestor of the ${{ inputs.branch }} branch. Please rebase it"
          exit 1
        fi
