name: 'Merge and upload coverage data'
description: 'Compresses and uploads the coverage data as an artifact'

runs:
  using: "composite"
  steps:
    - name: List coverage files
      shell: bash -euxo pipefail {0}
      run: find /tmp/coverage -type f -exec du -h {} \;

    - name: List pids for profraw
      shell: bash -euxo pipefail {0}
      run: |
        # lsof returns 1 if no one uses the file; xargs then returns 123
        pids=$(find /tmp/coverage -type f -print0 | xargs -0 lsof -t || true)
        for pid in ${pids[@]}; do
          echo "$pid: $(cat /proc/$pid/cmdline) ----"
          gdb -p $pid --batch -ex "thread apply all bt" || echo "gdb failed with $?"
          echo
        done

    - name: Merge coverage data
      shell: bash -euxo pipefail {0}
      run: scripts/coverage "--profraw-prefix=$GITHUB_JOB" --dir=/tmp/coverage merge

    - name: Download previous coverage data into the same directory
      uses: ./.github/actions/download
      with:
        name: coverage-data-artifact
        path: /tmp/coverage
        skip-if-does-not-exist: true # skip if there's no previous coverage to download

    - name: Upload coverage data
      uses: ./.github/actions/upload
      with:
        name: coverage-data-artifact
        path: /tmp/coverage
