name: 'Merge and upload coverage data'
description: 'Compresses and uploads the coverage data as an artifact'

runs:
  using: "composite"
  steps:
    - name: Merge coverage data
      shell: bash -ex {0}
      run: scripts/coverage "--profraw-prefix=$GITHUB_JOB" --dir=/tmp/neon/coverage/ merge

    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        retention-days: 7
        if-no-files-found: error
        name: coverage-data-artifact
        path: /tmp/neon/coverage/
