storage:
  vars:
    bucket_name: neon-storage-ireland
    bucket_region: eu-west-1
    console_mgmt_base_url: http://neon-stress-console.local
    env_name: neon-stress
    etcd_endpoints: neon-stress-etcd.local:2379
    safekeeper_enable_s3_offload: 'false'
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "{{ inventory_hostname }}"
    hostname_suffix: ".local"
    remote_user: admin
  children:
    pageservers:
      hosts:
        neon-stress-ps-1:
          console_region_id: aws-eu-west-1
        neon-stress-ps-2:
          console_region_id: aws-eu-west-1
    safekeepers:
      hosts:
        neon-stress-sk-1:
          console_region_id: aws-eu-west-1
        neon-stress-sk-2:
          console_region_id: aws-eu-west-1
        neon-stress-sk-3:
          console_region_id: aws-eu-west-1
