---
storage:
  vars:
    console_mgmt_base_url: http://console-release.local
    bucket_name: zenith-storage-oregon
    bucket_region: us-west-2
    broker_endpoint: http://storage-broker.prod.local:50051
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "{{ inventory_hostname }}"
    safekeeper_s3_prefix: prod-1/wal
    hostname_suffix: ".local"
    remote_user: admin
    sentry_environment: production

  children:
    pageservers:
      hosts:
        zenith-1-ps-2:
          console_region_id: aws-us-west-2
        zenith-1-ps-3:
          console_region_id: aws-us-west-2
        zenith-1-ps-4:
          console_region_id: aws-us-west-2
        zenith-1-ps-5:
          console_region_id: aws-us-west-2

    safekeepers:
      hosts:
        zenith-1-sk-1:
          console_region_id: aws-us-west-2
        zenith-1-sk-2:
          console_region_id: aws-us-west-2
        zenith-1-sk-4:
          console_region_id: aws-us-west-2
