---
storage:
  vars:
    env_name: prod-1
    console_mgmt_base_url: http://console-release.local
    bucket_name: zenith-storage-oregon
    bucket_region: us-west-2
    etcd_endpoints: zenith-1-etcd.local:2379
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "{{ inventory_hostname }}"
    hostname_suffix: ".local"
    remote_user: admin

  children:
    pageservers:
      hosts:
        zenith-1-ps-2:
          console_region_id: aws-us-west-2
        zenith-1-ps-3:
          console_region_id: aws-us-west-2

    safekeepers:
      hosts:
        zenith-1-sk-1:
          console_region_id: aws-us-west-2
        zenith-1-sk-2:
          console_region_id: aws-us-west-2
        zenith-1-sk-3:
          console_region_id: aws-us-west-2
