name: ZZZ Test Azure Build

on:
  pull_request:
    types:
      # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
      # Adding labeled to run when preview/xxx label added
      - opened
      - synchronize

jobs:
  build-image:
    permissions: # This is for Azure login to work.
      id-token: write
      contents: read
#    environment: dev
    name: Build image
    runs-on: ubuntu-latest
    steps:
      # two checkout steps follow, one when commit is specified, second when not.
      # if it makes sense be optimized to one step - feel free to do it.
      - name: Checkout from commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c  # v3.1.0

      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a  # @v2.1.1
        with:
          client-id: 4bb00e03-987d-4b86-a013-079729a85cb8
          tenant-id: c8350122-1697-4543-929a-d4a75d1bb552
          subscription-id: a57dcb0f-4249-4982-a872-1b73a7126c12

      - name: Login to ACR
        run: |
          az acr login --name=neoneastus2

      - name: Build image
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e  # v5.2.0
        with:
          context: .
          file: test.Dockerfile
          # Push to registry only if we're pushing commit to main or to release-forecasting
          push: true
          tags: neoneastus2.azurecr.io/chapson/neon:test-azure-build-neon-push
          cache-from: type=registry,ref=neondatabase/forecasting:cache
          provenance: false
          sbom: false
#
#  delete-deployments:
#    needs:
#      - build-image
#    name: Delete deployment
#    runs-on: ubuntu-latest
#    steps:
#      # two checkout steps follow, one when commit is specified, second when not.
#      # if it makes sense be optimized to one step - feel free to do it.
#      - name: Checkout from commit
#        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
#        with:
#          fetch-depth: 0
#
#      - name: Delete previous deployments
#        uses: ./.github/actions/delete-deployments
